import type { Metadata } from "next";
import "./globals.css";
import { cn } from "./common/libs/utils";
import { inter, jakartaSans } from "./common/libs/fonts";
import { ThemeProvider } from "./common/components/ThemeProvider";
import Header from "./common/components/header";
import AOS from "./common/components/AOS";
import "aos/dist/aos.css";
import Layout from "./common/components/layout";
import QueryClientProvider from "./common/components/QueryClientProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background relative font-sans antialiased",
          jakartaSans.className
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <QueryClientProvider>
            <Header />
            <Layout>{children}</Layout>
          </QueryClientProvider>
        </ThemeProvider>
        <AOS />
      </body>
    </html>
  );
}
